routes/web.php
<?php

use App\Http\Controllers\ProjectController;
use App\Http\Controllers\TaskController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('pages.welcome');
})->name('welcome');

Auth::routes();

Route::group(['middleware'=> 'auth'], function (){
    Route::put('task/updateAll', [TaskController::class, 'updateAll']);
    Route::resource('project', ProjectController::class)->except('show');
    Route::resource('task', TaskController::class)->except('show');
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

});

app/Models/Project.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
    protected $fillable = ['name'];

    public function tasks()
    {
        return $this->hasMany(Task::class);
    }
}

app/Http/Controllers/ProjectController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ProjectRequestForm;
use App\Models\Project;
use App\Repositories\ProjectRepository;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class ProjectController extends Controller
{
    private $projectRepository;
    private $resource = 'project';
    public function __construct(ProjectRepository $projectRepository)
    {
        view()->share('item', $this->resource);
        $this->projectRepository = $projectRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|Response|View|Application|Factory|View
     */
    public function index(Request $request)
    {
        $projects = $this->projectRepository->getAll($request);
        return \view('crud.index', compact('projects'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Application|Factory|Response|View
     */
    public function create()
    {
        return view('crud.create-edit');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param ProjectRequestForm $request
     * @return RedirectResponse
     */
    public function store(ProjectRequestForm $request)
    {
        $this->projectRepository->create($request->all());

        if ($request->has('add-new'))
            return redirect()->route('project.create')->withStatus(__('Project successfully created.'));

        return redirect()->route('project.index')->withStatus(__('Project successfully created.'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Project $project
     * @return Application|Factory|Response|View
     */
    public function edit(Project $project)
    {
        return view('crud.create-edit', compact('project'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param ProjectRequestForm $request
     * @param $id
     * @return RedirectResponse
     */
    public function update(ProjectRequestForm $request ,$id)
    {
        $this->projectRepository->update($id,$request->all());

        if ($request->has('add-new'))
            return redirect()->route('project.edit',$id);

        return redirect()->route('project.index')->withStatus(__('Project successfully Updated.'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param $id
     * @return RedirectResponse
     */
    public function destroy($id)
    {
        $this->projectRepository->delete($id);

        return redirect()->route('project.index')->withStatus(__('Project successfully deleted.'));
    }
}

resources/views/project/_form.blade.php
<x-text :name="'name'" :oldValue="$entity ?? null" :required="true"></x-text>

resources/views/project/_table.blade.php
<div class="table-responsive py-4">
    <table class="table align-items-center table-flush"  id="datatable-basic">
        <thead class="thead-light">
        <tr>
            <th scope="col">#</th>
            <th scope="col">{{ __('Name') }}</th>
            <th scope="col">{{ __('Created At') }}</th>
            <th scope="col">{{ __('Actions') }}</th>
        </tr>
        </thead>
        <tbody>

        @foreach ($projects as $project)
            <tr>
                <td>
                     {{ $loop->index + 1 }}
                </td>
                <td>{{ $project->name }}</td>

                @if($project->created_at)
                    <td>{{ $project->created_at->format('d/m/Y H:i') }}</td>
                @endif

                <td class="table-actions">
                    <a href="{{ route('project.edit', $project) }}" class="table-action" data-toggle="tooltip" data-original-title="Edit Project">
                        <i class="fas fa-user-edit"></i>
                    </a>

                    <form action="{{ route('project.destroy', $project) }}" method="post" style="display: inline-block">
                        @csrf
                        @method('delete')
                        <a href="#!" class="table-action" data-toggle="tooltip" data-original-title="Delete Project" onclick="confirm('{{ __("Are you sure you want to delete this project?") }}') ? this.parentElement.submit() : ''">
                            <i class="fas fa-trash"></i>
                        </a>
                    </form>
                </td>
            </tr>
        @endforeach
        @if($projects == null)
            <p class="text-center mt-5">There is no data to show.</p>
        @endif
        </tbody>
    </table>

</div>