routes/web.php
<?php

use App\Http\Controllers\ProjectController;
use App\Http\Controllers\TaskController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('pages.welcome');
})->name('welcome');

Auth::routes();

Route::group(['middleware'=> 'auth'], function (){
    Route::put('task/updateAll', [TaskController::class, 'updateAll']);
    Route::resource('project', ProjectController::class)->except('show');
    Route::resource('task', TaskController::class)->except('show');
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

});

resources/views/layouts/navbars/navbar.blade.php
@if(auth()->check() && !in_array(request()->route()->getName(), ['welcome', 'page.pricing', 'page.lock']))
    @include('layouts.navbars.navs.auth')
@endif
    
@if(!auth()->check() || in_array(request()->route()->getName(), ['welcome', 'page.pricing', 'page.lock']))
    @include('layouts.navbars.navs.guest')
@endif

resources/views/layouts/navbars/sidebar.blade.php
<nav class="sidenav navbar navbar-vertical fixed-left navbar-expand-xs navbar-light bg-white" id="sidenav-main">
    <div class="scrollbar-inner scroll-scrollx_visible">
        <div class="sidenav-header d-flex align-items-center">
            <a class="navbar-brand" href="{{ route('home') }}">
                <h1 class="font-weight-700 header">Draggable</h1>
            </a>
            <div class="ml-auto mb-2">
                <!-- Sidenav toggler -->
                <div class="sidenav-toggler d-none d-xl-block" data-action="sidenav-unpin" data-target="#sidenav-main">
                    <div class="sidenav-toggler-inner">
                        <i class="sidenav-toggler-line"></i>
                        <i class="sidenav-toggler-line"></i>
                        <i class="sidenav-toggler-line"></i>
                    </div>
                </div>
            </div>
        </div>

        <div class="navbar-inner mb-4">
            <!-- Collapse -->
            <div id="sidenav-collapse-main">
                <!-- Nav items -->
                <i class="ni ni-shop text-primary"></i>
                <a  href="{{ route('project.index','Project') }}" class="nav-link" style="display: inline-block">{{ __('List Projects') }}</a>
            </div>
        </div>

        <div class="navbar-inner mb-4">
            <!-- Collapse -->
            <div id="sidenav-collapse-main">
                <!-- Nav items -->
                <i class="ni ni-shop text-primary"></i>
                <a  href="{{ route('task.index','Task') }}" class="nav-link" style="display: inline-block">{{ __('List Tasks') }}</a>
            </div>
        </div>
    </div>
</nav>